// <auto-generated />
using BakeryWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakeryWebApp.Migrations
{
    [DbContext(typeof(BakeryContext))]
    partial class BakeryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BakeryWebApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bread"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Bun"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Muffin"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cake"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Cookie"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Pie"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Flour"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Meal"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Pizza"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Seasonal"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Cafe"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Square"
                        });
                });

            modelBuilder.Entity("BakeryWebApp.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            CategoryId = 1,
                            GroupName = "Cheese"
                        },
                        new
                        {
                            GroupId = 2,
                            CategoryId = 2,
                            GroupName = "Cheese"
                        },
                        new
                        {
                            GroupId = 3,
                            CategoryId = 1,
                            GroupName = "Rice"
                        },
                        new
                        {
                            GroupId = 4,
                            CategoryId = 1,
                            GroupName = "Toasted Oat"
                        });
                });

            modelBuilder.Entity("BakeryWebApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BakeryWebApp.Models.Group", b =>
                {
                    b.HasOne("BakeryWebApp.Models.Category", "GroupCategory")
                        .WithMany("Groups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCategory");
                });

            modelBuilder.Entity("BakeryWebApp.Models.Product", b =>
                {
                    b.HasOne("BakeryWebApp.Models.Group", "ProductGroup")
                        .WithMany("Products")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductGroup");
                });

            modelBuilder.Entity("BakeryWebApp.Models.Category", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("BakeryWebApp.Models.Group", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
